version: "3.5"

services:
  database:
    image: postgres:10
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=olx
      - POSTGRES_PASSWORD=olx@0703
      - POSTGRES_DB=db_olx
    ports:
      - 5432:5432
    volumes:
      - "tcb-postgres:/var/lib/postgresql/data"
volumes:
  tcb-postgres:
