app:
  nomeArquivo: 'fatura_itau_gold.csv'
  diretorioArquivo: '/home/thiago/develop/thiago/gerencia-fatura-cartao/'
  email:
    from: monitora.olx@gmail.com
spring:
  mail:
    host: smtp.gmail.com
    password: MonitoraOLX5987
    port: 587
    username: ${app.email.from}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
  datasource:
    url: jdbc:postgresql://localhost/db_gerenciar_fatura
    username: app
    password: app@070335
    driverClassName: org.postgresql.Driver
  jpa:
    showSql: false
    hibernate:
      ddlAuto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    baseline-on-migrate: true
