app:
  cronScheduler: 0 0/2 * * * *
  email:
    from: monitora.olx@gmail.com
  telegram:
    baseUrl: https://api.telegram.org/
    token: XXX
    chatId: XXX
spring:
  mail:
    host: smtp.gmail.com
    password: XXX
    port: 587
    username: ${app.email.from}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
  datasource:
    url: jdbc:postgresql://localhost/db_olx
    username: olx
    password: olx@0703
    driverClassName: org.postgresql.Driver
  jpa:
    showSql: false
    hibernate:
      ddlAuto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    baseline-on-migrate: true
